scrape_configs:
  - job_name: 'RecipientJob'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'My Spring Boot Application'
  - job_name: 'VisualizerJob'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]
        labels:
          application: 'My Spring Boot Application 2'