apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
        - name: sender
          image: omeganessy/sender:version2
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: sender
spec:
  selector:
    app: sender
  type: ClusterIP
  ports:
    - port: 8080
