apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    orgId: 1
    access: proxy
    typeName: Prometheus
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: POST
    readOnly: false
    uid: adwvewd4gto8wc
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prometheus:9090
