apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-collector
  labels:
    app: collector
    env: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collector
      env: green
  template:
    metadata:
      labels:
        app: collector
        env: green
    spec:
      containers:
        - name: collector
          image: omeganessy/collector:version9
          ports:
            - containerPort: 8082