server:
  port: 8083

spring:
  application:
    name: micro-visualizer
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate
  datasource:
    username: pass
    password: pass
    url: jdbc:postgresql://postgres.default.svc.cluster.local:5432/messages_db

management:
  endpoints:
    web:
      exposure:
        include: "*"