apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualizer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualizer
  template:
    metadata:
      labels:
        app: visualizer
    spec:
      containers:
        - name: visualizer
          image: omeganessy/visualizer:latest
          ports:
            - containerPort: 8083

---

apiVersion: v1
kind: Service
metadata:
  name: visualizer
  labels:
    app: visualizer
spec:
  type: ClusterIP
  ports:
    - port: 8083
  selector:
    app: visualizer