apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-recipient
  labels:
    app: recipient
    env: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipient
      env: blue
  template:
    metadata:
      labels:
        app: recipient
        env: blue
    spec:
      containers:
        - name: recipient
          image: omeganessy/recipient:latest
          ports:
            - containerPort: 8081